FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

# Change here the command, how I run the docker in production
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]